# Generated by Django 3.2.4 on 2021-08-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alpha2code', models.CharField(max_length=16)),
                ('capital', models.CharField(max_length=32)),
                ('population', models.IntegerField()),
                ('timezones', models.CharField(max_length=16)),
                ('flag', models.CharField(max_length=64)),
                ('languages', models.CharField(max_length=256)),
                ('borders', models.CharField(max_length=256)),
            ],
        ),
    ]
